#########################################################
#File For Naming Character
#########################################################

###Default Name
#define fn = Character(_("Hiroyuki"), color = "#ffffff")
#define ln = Character(_("Nishimura"), color = "#ffffff")

##Main Characters
define ko = Character(_("Kounosuke"), color = "#ab8613", what_color = "#ab8613")
define ta = Character(_("Tatsuki"), color = "#109d10", what_color = "#109d10")
define su = Character(_("Shun"), color = "#08ceff", what_color = "#08ceff")
define ka = Character(_("Kouya"), color = "#828490", what_color = "#828490")
define ju = Character(_("Juuichi"), color = "#a14214", what_color = "#a14214")
define si = Character(_("Shin"), color = "#9d3cff", what_color = "#9d3cff")
define so = Character(_("Soutarou"), color = "#fee13b", what_color = "#fee13b") 
define ky = Character(_("Kyouji"), color = "#066afe", what_color = "#066afe")
define to = Character(_("Torahiko"), color = "#fece0a", what_color = "#fece0a")

##Side Characters & Combos

define am = Character(_("Amaki"), color = "#ffffff", what_color = "#ffffff")
define tp = Character(_("Tappei"), color = "#ffffff", what_color = "#ffffff")
define horse = Character(_("Horseman"), color = "#ffffff", what_color = "#ffffff")
define bird = Character(_("Birdman"), color = "#ffffff", what_color = "#ffffff")
define cat = Character(_("Catman"), color = "#ffffff", what_color = "#ffffff")
define ni = Character(_("Nikaidou"), color = "#ffffff", what_color = "#ffffff")
define rat = Character(_("Rat Boy"), color = "#ffffff", what_color = "#ffffff")
define cu = Character(_("Chuukichi"), color = "#ffffff", what_color = "#ffffff")
define boy = Character(_("Boy"), color = "#ffffff", what_color = "#ffffff") 
define yk = Character(_("Yukiharu"), color = "#ffffff", what_color = "#ffffff") 
define bo = Character(_("Botan"), color = "#f2c784", what_color = "#f2c784")
define brothers = Character(_("Kou & Yuki"), color = "#ffffff", what_color = "#ffffff")
define fntora = Character(_("You & Tora"), color = "#ffffff", what_color = "#ffffff")
define torashun = Character(_("Tora & Shun"), color = "#ffffff", what_color = "#ffffff") 
define fnsu = Character(_("You & Shun"), color = "#ffffff", what_color = "#ffffff") 
define fnsi = Character(_("You & Shin"), color = "#ffffff", what_color = "#ffffff") 
define kosu =  Character(_("Kouno & Shun"), color = "#ffffff", what_color = "#ffffff") 
define allthree = Character(_("All Three"), color = "#ffffff", what_color = "#ffffff") 
define everybody = Character(_("Everybody"), color = "#ffffff", what_color = "#ffffff")
define na = Character(_("Nanafuse"), color = "#ffffff", what_color = "#ffffff")
define gk = Character(_("Gaku"), color = "#ffffff", what_color = "#ffffff")
define wolf = Character(_("Wolf"), color = "#ffffff", what_color = "#ffffff")
define tn = Character(_("Ten"), color = "#ffffff", what_color = "#ffffff")
define te = Character(_("Tetsuya"), color = "#ffffff", what_color = "#ffffff")
define ke = Character(_("Keisuke"), color = "#ffffff", what_color = "#ffffff")
define yu = Character(_("Yuuki"), color = "#ffffff", what_color = "#ffffff")
define jn = Character(_("Jun"), color = "#ffffff", what_color = "#ffffff")
define sg = Character(_("Shigure"), color = "#ffffff", what_color = "#ffffff")
define tato = Character(_("Tatsu & Tora"), color = "#ffffff", what_color = "#ffffff")
define tako = Character(_("Tatsu & Kouno"), color = "#ffffff", what_color = "#ffffff")
define toko = Character(_("Tora & Kouno"), color = "#ffffff", what_color = "#ffffff")
define kyju = Character(_("Kyou & Juu"), color = "#ffffff", what_color = "#ffffff")
define friend = Character(_("Friend"), color = "#ffffff", what_color = "#ffffff")
define suso = Character(_("Shun & Sou"), color = "#ffffff", what_color = "#ffffff")
define ykfr = Character(_("Yuki's Friend"), color = "#ffffff", what_color = "#ffffff")
define jufn = Character(_("Juu & [fn]"), color = "#ffffff", what_color = "#ffffff")
define fnky = Character(_("[fn] & Kyouji"), color = "#ffffff", what_color = "#ffffff")
define kyka = Character(_("Kyouji & Kouya"), color = "#ffffff", what_color = "#ffffff")
define mi = Character(_("Mitsuhisa"), color = "#ffffff", what_color = "#ffffff")
define kato = Character(_("Kouya & Tora"), color = "#ffffff", what_color = "#ffffff")
define both = Character(_("Both"), color = "#ffffff", what_color = "#ffffff")
define captain = Character(_("Captain"), color = "#ffffff", what_color = "#ffffff")

##Faceless Characters
define mom = Character(_("Mom"), color = "#ffffff", what_color = "#ffffff")
define driver = Character(_("Driver"), color = "#ffffff", what_color = "#ffffff")
define who = Character(_("???"), color = "#ffffff", what_color = "#ffffff")
define gm = Character(_("Grandma"), color = "#ffffff", what_color = "#ffffff")
define gp = Character(_("Grandpa"), color = "#ffffff", what_color = "#ffffff")
define gps = Character(_("Grandparents"), color = "#ffffff", what_color = "#ffffff")
define om = Character(_("Old Man"), color = "#ffffff", what_color = "#ffffff")
define ow = Character(_("Old Woman"), color = "#ffffff", what_color = "#ffffff")
define clerk = Character(_("Clerk"), color = "#ffffff", what_color = "#ffffff")
define shopkeep = Character(_("Shopkeeper"), color = "#ffffff", what_color = "#ffffff")
define yukino = Character(_("Yukino"), color = "#ffffff", what_color = "#ffffff")
define harue = Character(_("Harue"), color = "#ffffff", what_color = "#ffffff")
define narr = Character(_("Narration"), color = "#ffffff", what_color = "#ffffff")
define hwa = Character(_("Housewife A"), color = "#ffffff", what_color = "#ffffff")
define hwb = Character(_("Housewife B"), color = "#ffffff", what_color = "#ffffff")
define ryo = Character(_("Ryo"), color = "#ffffff", what_color = "#ffffff")
define bystanders = Character(_("Bystanders"), color = "#ffffff", what_color = "#ffffff")
define farmer = Character(_("Farmer"), color = "#ffffff", what_color = "#ffffff")
define everyone = Character(_("Everyone"), color = "#ffffff", what_color = "#ffffff")
define attendant = Character(_("Attendant"), color = "#ffffff", what_color = "#ffffff")
define door = Character(_("Door"), color = "#ffffff", what_color = "#ffffff")
define phone = Character(_("Phone"), color = "#ffffff", what_color = "#ffffff")
define note = Character(_("Note"), color = "#ffffff", what_color = "#ffffff")
define kz = Character(_("Kazumi"), color = "#ffffff", what_color = "#ffffff")
define mc = Character(_("MC"), color = "#ffffff", what_color = "#ffffff")
define judge = Character(_("Judge"), color = "#ffffff", what_color = "#ffffff")
define clubmem = Character(_("Club Member"), color = "#ffffff", what_color = "#ffffff")


